### ISSUE TITLE
Renew ssl certificate

### ISSUE THREAD

**Issue by promit2014** [beameio/beame-insta-ssl#16]
I have earlier saved my certificate as per the instruction in the email in my test system . Now my system crashed and I have another system running the application but when I again tried to save my certificate in my new system it is giving me an error that the token has expired. Is there a way to get a new certificate or renew the token . I tried signup again with the same email . I am getting there error too that email already exists . Can you please help me out on this .

**Comment by sophiabeame** [comment]
Hi! What you received in the email was not a certificate, but a token.  We will never send you a certificate by email. The email had some instructions on how to run a couple commands to use the token to generate your certificate. Here's what we'll do. Since you emailed me about this directly, I will remove your registration record so you can register again. Tokens expire after a couple days for security purposes. When you re-register, you'll get another token with instructions and you can use them to generate the new certificate. The old token won't work. Looking forward to hearing about your use case!
