### ISSUE TITLE
[ProvisionApi] FATAL: Post to provision failed

### ISSUE THREAD

**Issue by ghost** [beameio/beame-insta-ssl#41]
Hi,

I'm running into the below issue when trying to install beame-insta-ssl:

$ beame-insta-ssl creds getCreds --regToken 'my token here'
[BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[ProvisionApi] FATAL: Post to provision failed

$ beame-insta-ssl tunnel make --dst 3000 --proto http
Hi.

Currently, you have no certificates. You must have at least one
certificate to operate a tunnel.
......

Here is my environment:

$ node -v
v7.9.0
$ npm -v
4.2.0
$ openssl version
OpenSSL 1.0.2k  26 Jan 2017
$ which openssl
/usr/bin/openssl
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
      .....

Please note that I already upgrade OpenSSL to the version 1.0.2k.

Could you please look into the issue?

Thanks,
Ky

**Comment by AlexzxelA** [comment]
Hi Ky,
Please create new registration token (on the same registration page) and retry, the one you used seems expired.
Cheers,
Alex

**Comment by ghost** [comment]
Hi Alex,

I just registered a new email address and tried again but still no luck.
I still run into the same issue:
[BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[ProvisionApi] FATAL: Post to provision failed

Thanks,
Ky

**Comment by ilyash** [comment]
Hi.

Please follow these steps:

* Get new token as your existing tokens have expired (valid only for 48 hours). You can use your-email+01@example.com to get token to your-email@example.com.
* Please try with NodeJS 6. We test with NodeJS 6 because it's LTS. While theoretically beame-insta-ssl should work with NodeJS 7, it was not tested. Instead of running `beame-insta-ssl creds getCreds --regToken 'my token here'` please run `BEAME_LOG_LEVEL=DEBUG beame-insta-ssl creds getCreds --regToken 'my token here'`.
* Post the complete output of the command here (censoring the token and possibly your FQDN).

**Comment by ghost** [comment]
Hi @ilyash,

I registered a new token and it works now with the NodeJS 7.
Please note that that new token is a Beame SDK one, not a beame-insta-ssl.
So I guess there might be some differences between SDK and Insta-SSL?!

Thanks in advance.

Regards,
Ky

**Comment by Agit-coder** [comment]
-
